apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: briankim0809/my_blog_backend:firsttry
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@db-service:5432/blogdb



